### ISSUE TITLE
Jest unit test case will execute before executing actuall function so getting error in expect part

### ISSUE THREAD

**Issue by anjneeksharma** [graphql/graphql-js#2599] opened 2020-06-01 17:05 UTC
AddingFeedback will not execute fully by the time all the test cases will execute

it('addFeedback should create a feedback', done => {
request
.post('/graphql')
.send({
query: query,
operationName: 'AddingFeedback',
variables: {
input: mock
}
})
.expect(res => {
expect(res.body).not.toHaveProperty('errors');
expect(res.body).toHaveProperty('data');
expect(res.body.data).toHaveProperty('addFeedback');
expect(res.body.data.addFeedback).toHaveProperty('_id', mock._id);
expect(res.body.data.addFeedback).toHaveProperty('description', mock.description);
expect(res.body.data.addFeedback).toHaveProperty('ticketID', mock.ticketID);
expect(res.body.data.addFeedback).toHaveProperty('experience', mock.experience);
})
.end((err, res) => {
done(err);
});
});

**Comment by danielrearden** [comment] 2020-06-04 01:30
Duplicate of #2598

**Closed by danielrearden** 2020-06-04 01:30 UTC
