### ISSUE TITLE
Fields in a selection set of a field in a query override other fields in the selection set of the same field in a fragment

### ISSUE THREAD

**Issue by cagdastulek** [graphql/graphql-js#1060] opened 2017-10-10 22:05 UTC
In a query, if I use a fragment and then add some extra fields to the query, they are merged successfully as expected.

However, if one of the fields itself is a selection set, then the final merged field does not have fields from the fragment anymore. It only has the fields defined in the query.

Example:
```gql
query BarQuery {
  bar {
    ...FooFragment
    fieldD
    fieldC {
       f3
    }
  }
}

fragment FooFragment on Bar {
  fieldA
  fieldB
  fieldC {
    f1
    f2
  }
}
```

The final query is:

```gql
query BarQuery {
  bar {
    fieldA
    fieldB
    fieldD
    fieldC {
       f3
    }
  }
}
```

I would expected fieldC selection set to have all fields: f1, f2, f3

If the order is changed, that is, the fragment is put after the fields defined in the query, then the final query has the union of all fields defined in the selection set of fieldC.

That is:
```gql
query BarQuery {
  bar {
    fieldA
    fieldB
    fieldD
    fieldC {
       f1
       f2
       f3
    }
  }
}
```

I am not sure if this is a bug or by design, though. I checked the spec and couldn't find any rule around that.

**Comment by leebyron** [comment] 2017-12-07 06:50
This would be a bug, however I cannot reproduce what you've described here.

I'm going to close this issue since I cannot reproduce it, however if you can please please open a PR with a failing test case so it can get attention

**Closed by leebyron** 2017-12-07 06:50 UTC
