### ISSUE TITLE
[SDL] Deprecation reason cannot be just any string

### ISSUE THREAD

**Issue by bessey** [graphql/graphql-js#1363] opened 2018-05-31 13:47 UTC
I just upgraded a repo to use the latest graphql-js (0.13.2 at time of writing) and have found that my SDL cannot be parsed, because my deprecated reason strings have commas in them:

```gql
type LocalResource implements Node {
  amenities: AmenitySet @deprecated(reason: "Example, broken, string")
}
```

Which leads to error:

```
GraphQLError: Syntax Error: Unterminated string.
    at syntaxError (http://localhost:6006/static/preview.bundle.js:160095:10)
    at readString (http://localhost:6006/static/preview.bundle.js:99692:32)
    at readToken (http://localhost:6006/static/preview.bundle.js:99478:14)
    at Object.lookahead (http://localhost:6006/static/preview.bundle.js:99240:43)
    at Object.advanceLexer [as advance] (http://localhost:6006/static/preview.bundle.js:99231:33)
    at expect (http://localhost:6006/static/preview.bundle.js:41335:11)
    at parseConstArgument (http://localhost:6006/static/preview.bundle.js:40381:13)
    at many (http://localhost:6006/static/preview.bundle.js:41387:16)
    at parseArguments (http://localhost:6006/static/preview.bundle.js:40360:50)
    at parseDirective (http://localhost:6006/static/preview.bundle.js:40625:16)
```

This isn't mentioned in the spec as being invalid as far as I can see.

**Comment by bessey** [comment] 2018-05-31 14:53
Hmm, perhaps this isnt a `graphql-js` bug. My GraphiQL works fine even when I go and look at these deprecation messages in the Docs. but it does crash my `apollo-tools` `makeExecutableSchema`

**Comment by IvanGoncharov** [comment] 2018-05-31 14:58
> This isn't mentioned in the spec as being invalid as far as I can see.

@bessey You right it's valid.
But I can't reproduce it using your snippet 😞 

You can try to find where error catched and do `String(error)` when you will get error like this:
```
  Syntax Error: Unterminated string.

  GraphQL request (2:70)
  1: type LocalResource implements Node {
  2:   amenities: AmenitySet @deprecated(reason: "Example, broken, string)
                                                                          ^
  3: }
```
It can help you to locate error in your SDL.

If it doesn't help please try to minify your SDL file and post it here.

**Comment by IvanGoncharov** [comment] 2018-05-31 16:30
> but it does crash my apollo-tools makeExecutableSchema

I think you should report it in their repo.

**Comment by IvanGoncharov** [comment] 2018-06-08 16:20
@bessey Can I close this issue?

**Comment by bessey** [comment] 2018-06-09 09:57
Yes

**Closed** 2018-06-09 16:48 UTC
