### ISSUE TITLE
Unable to build schema using buildSchema

### ISSUE THREAD

**Issue by schandrasekhar** [graphql/graphql-js#2466] opened 2020-02-29 00:40 UTC
# Questions regarding how to use GraphQL
I am using `buildSchema` function to build a schema object from string. Its is not working as expected after upgrading to graphql-java v14 and graphql-js v14

# Reporting issues with GraphQL.js
My schema end point returns this string
```
"Directs the executor to include this field or fragment only when the if argument is true"
directive @include(
"Included when true."
if: Boolean!
) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Directs the executor to skip this field or fragment when the if 'argument is true."
directive @Skip(
"Skipped when true."
if: Boolean!
) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Marks the field or enum value as deprecated"
directive @deprecated(
"The reason for the deprecation"
reason: String = "No longer supported"
) on FIELD_DEFINITION | ENUM_VALUE

union streamItem = Ad | Content | EditorialPackage | EntityCard
.
.
.
.
```
when trying to build schema object using

`const buildSchema = require('graphql').buildSchema; `
` const schema = buildSchema(schemaString);`

i am getting this error
```
{ GraphQLError: Syntax Error GraphQL request (5:1) Unexpected String "Directs the executor to include this field or fragment only when the ifargument is true" 4: 5: "Directs the executor to include this field or fragment only when the if argument is true" ^ 6: directive @include( at syntaxError (/node_modules/graphql/error/syntaxError.js:31:15) at unexpected (/node_modules/graphql/language/parser.js:996:33) at parseDefinition (/node_modules/graphql/language/parser.js:155:9) at parseDocument (node_modules/graphql/language/parser.js:109:22) at parse (/node_modules/graphql/language/parser.js:46:10) at buildSchema (/node_modules/graphql/utilities/buildASTSchema.js:469:43) at getRequest.then (/src/schema.js:42:32) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7) message: 'Syntax Error GraphQL request (5:1) Unexpected String "Directs the executor to include this field or fragment only when theifargument is true"\n\n4: \n5: "Directs the executor to include this field or fragment only when theif` argument is true"\n ^\n6: directive @include(\n',
locations: [ { line: 5, column: 1 } ],
path: undefined }

```

this is my package json
```
"dependencies": {
"env": "0.0.2",
"express": "4.17.1",
"express-graphql": "0.9.0",
"graphql": "14.6.0",
"path": "0.12.7"
},
```
Earlier in the schema string a comment was represented as `# dummy comment`, but now it is sent as `"dummy comment"`. Is `buildSchema` not able to handle the comments or am I doing something wrong ?

**Comment by IvanGoncharov** [comment] 2020-03-02 15:48
@schandrasekhar `buildSchema` should work with string descriptions.
Can you please do:
```
console.log(require('graphql').version);
```
and post result here?

**Comment by IvanGoncharov** [comment] 2020-05-06 11:32
Closing since I can't reproduce it and no additional details was provided

**Closed by IvanGoncharov** 2020-05-06 11:32 UTC
Labels: question
