### ISSUE TITLE
Error logged to console on resolver promise rejection

### ISSUE THREAD

**Issue by BRMC888** [graphql/graphql-js#1101] opened 2017-11-29 00:32 UTC
I return a promise in my graphql resolvers, I resolve the promise when the query was successful - which works fine, but whenever I reject a promise, an un-mutable, seemingly un-handleable error is thrown in the server console.

For example, I use a mutation to handle a user Login, if the username does not exist in the db, I call reject with the message "User does not exist"

My console then looks like this:

> GraphQLError: User does not exist
> &nbsp;&nbsp;&nbsp;&nbsp;at locatedError (/Users/..project../node_modules/graphql/error/locatedError.js:23:10)
> &nbsp;&nbsp;&nbsp;&nbsp;at /Users/..project../node_modules/graphql/execution/execute.js:550:55
> &nbsp;&nbsp;&nbsp;&nbsp;at \<anonymous\>
> &nbsp;&nbsp;&nbsp;&nbsp;at process._tickCallback (internal/process/next_tick.js:188:7)
> 

I have looked everywhere and cannot find how to stop this error being thrown, I don't need or want it in my console for every rejection, I hope this isn't me overlooking something simple, thanks for any help!

**Comment by leebyron** [comment] 2017-12-07 06:43
I believe this should be fixed in the master build. If you would like to try that, there are instructions on the readme for using the latest build.

If you still encounter this issue, it would be helpful to send a PR showing a failing test case

**Closed by leebyron** 2017-12-07 06:43 UTC

**Comment by BRMC888** [comment] 2018-02-18 17:36
I've just used the master build, a few months on, the problem is still there, however the message has changed slightly, the same error as my original post now reads:

> Error: User does not exist
    &nbsp;&nbsp;&nbsp;&nbsp;at asErrorInstance (/Users/..project../node_modules/graphql/execution/execute.js:545:43)
    &nbsp;&nbsp;&nbsp;&nbsp;at \<anonymous\>
    &nbsp;&nbsp;&nbsp;&nbsp;at process._tickCallback (internal/process/next_tick.js:188:7)

I'm relatively new to GitHub, you'll have to explain what a 'PR' is and how I can send one

**Comment by leebyron** [comment] 2018-02-18 21:38
A PR is how open source projects evolve! It’s how we share code. Check out https://help.github.com/articles/about-pull-requests/

With what I know from your report as is, it’s hard for me to tell you what might be wrong with your code. If you can reduce the code with a problem down to the smallest case causing an issue, then you can share it as a PR to help illustrate what might be a bug you’ve found, or can help someone better explain a usage pattern to help. 

Typically errors are only logged to console if they’re explicitly console.log’d somewhere In your code or if they’re uncaught and reported by node

**Comment by BRMC888** [comment] 2018-03-18 02:32
Thanks for the info,

I've made a repo with the bare minimum to see the error I'm getting in context

Again, I'm new to GitHub, not sure if this is what you wanted but hope it's useful

**Comment by IvanGoncharov** [comment] 2018-03-18 10:10
@BRMC888 Your issue caused by `apollo-server`, here is the line that prints error messages:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/runQuery.ts#L80
Please report this issue to that repo.
