### ISSUE TITLE
Subscription not working with alias

### ISSUE THREAD

**Issue by joseph-d-p** [graphql/graphql-js#1846] opened 2019-05-03 03:18 UTC
When using `alias`, subscription doesn't work.
It works normally without `alias` as expected.

```
subscription OnPutItem($id: ID!) {
  item: onPutItem(id: $id) { // <---------- with alias
    id
    data
  }
}

mutation PutItem($data: String!) {
  item: PutItem(data: $data) { // <-------- with alias
    id
    data
  }
}
```

Any thoughts?

**Comment by IvanGoncharov** [comment] 2019-05-03 09:02
@joseph-d-p I tested it works fine.
Can please share your minimal reproduce example?

**Comment by joseph-d-p** [comment] 2019-05-03 10:08
@IvanGoncharov 

So the output I got was without the alias (i.e. `item`). It shows the `onPutItem` instead.
```
{
  data: {
     onPutItem: { // <--- expecting it to be item (alias)
      ....
      }
   }
}
```

**Comment by IvanGoncharov** [comment] 2019-05-03 12:56
@joseph-d-p I mean minimal code sample using `graphql-js` that reproduces your issue.
Can you do that?

**Comment by IvanGoncharov** [comment] 2019-05-27 10:12
@joseph-d-p Closing since I can't reproduce it. 
Please feel free to open the new one if you can come up with a minimal code sample using `graphql-js` that reproduces your issue.

**Closed by IvanGoncharov** 2019-05-27 10:12 UTC
Labels: question
