### ISSUE TITLE
Performance of stack traces in errors results in high response latency (>1 second)

### ISSUE THREAD

**Issue by ajhenry** [graphql/graphql-js#4028] opened 2024-03-12 21:35 UTC
Great work y'all are doing here! We've run into a bit of a snag dealing with errors and stack traces. 

The problem:
As bundle size increases, the duration of calculating a stack trace with source maps of an error thrown during resolver execution takes more time to compute. 

We narrowed down the culprit to the following check:
https://github.com/graphql/graphql-js/blob/9c90a23dd430ba7b9db3d566b084e9f66aded346/src/error/GraphQLError.ts#L144-L158

We did a flame graph for an error thrown and this resulted in the following:

![Image](https://github.com/graphql/graphql-js/assets/24923406/c7cf0e8f-82e5-4153-b133-60f412044e6e)
![Image](https://github.com/graphql/graphql-js/assets/24923406/980edacc-267b-45ed-b8af-6cf24bfb0ff4)

It takes this amount of time regardless of which resolver throws an error.

We currently bundle our server (along with tree-shaken dependencies) in a single file so we can upload it to a lambda. We are at around 76MB for our total bundled file which is not great (😟) but still very usable for us in production. 

Our workaround right now is to explicitly set `captureStackTrace` and bypass having to perform this calculation. This decreases the execution time from `1154ms ` to `20ms`. However, we are left with no stack traces. 

Any suggestions or help would be greatly appreciated, thanks!

**Comment by yaacovCR** [comment] 2024-03-29 06:15
Duplicate of #2800 ?
That issue suggests disabling source maps?

**Comment by JoviDeCroock** [comment] 2024-10-11 07:23
So doing `Error().stack` which is the fallback when not calling `captureStackTrace` doesn't take up this much compute? We could just always leverage `Error().stack` and filter out the `GraphQLError` line which is essentially all that `captureStackTrace` should be doing here.

**Closed** 2024-10-14 15:07 UTC
