### ISSUE TITLE
Flow types under-specified for visit() `enter`/`leave` methods under a specific kind.

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-js#1168] opened 2017-12-18 17:41 UTC
Example which should not encounter a type error, but does:

    visit(doc, {
      FragmentDefinition: {
        enter(node) {
          console.log(node.name.value);
        },
      })

**Comment by IvanGoncharov** [comment] 2018-09-03 18:50
Can't reproduce on master with Flow `0.79` looks like it was fixed by Flow update.

**Closed by IvanGoncharov** 2018-09-03 18:50 UTC
