### ISSUE TITLE
Loading data in resolver function does not resolve

### ISSUE THREAD

**Issue by ed-zm** [graphql/graphql-js#820] opened 2017-04-20 15:58 UTC
Hello, I've been stucked for a while trying to retrieve data from a dynamodb database using dynogels. 
this is my graphql function:
```
return graphql.graphql(schema, query)
    .then((response) => cb(null, createResponse(200, response)))
    .catch((err) => cb(createResponse(500, {"message": "Internal server error :("})));
```

and this is my resolver function: 

```
resolve: (obj, args, context) =>{
    return customersTable
    .scan()
    .execAsync()
    .then(res => {
      if(res){
        console.log('res', res)
        return res
      } else {
        console.log('null')
        return null
      }
    })
  }

```
Also I made it in this way

```
const getItems = (table) => { 
  return new Promise((resolve, reject) =>
    table
    .scan()
    .exec((err, res) =>{
      console.log('entro aqui')
      if(err){
        return reject()
      }
      items = res.Items.map((item) => {
        return item.attrs
      })
      return resolve(items)
    })
  )
}

```

```
resolve: (obj, args, context) =>
    getItems(customersTable)

```
And this way: 
```
resolve: async (obj, args, context) =>{
    const response = await getItems(customersTable)
    return response
}
```
Even I tried to test with a setTimeout:

```
resolve: (obj, args, context) =>
    new Promise((resolve, reject) => setTimeout(() => resolve([]), 1000))
```

but it does not wait for the async task. So, how graphql handle resolving promises inside the resolver promise? thanks in advance

**Comment by cosmosgenius** [comment] 2017-04-25 13:29
The resolver will only be called if the respective field is requested. Can you provide a sample schema and query for which it fails?

**Comment by leebyron** [comment] 2017-05-18 15:33
If a Promise is returned from a resolver, the executor will wait on that value to resolve before continuing.

Closing this issue since it's aging, if you're still having issues feel free to reopen and include more information about the issue you're facing so someone can reproduce it. Bonus if you can send a failing test.

**Closed by leebyron** 2017-05-18 15:33 UTC
