### ISSUE TITLE
Possible execution optimization?

### ISSUE THREAD

**Issue by mduarte** [graphql/graphql-js#161] opened 2015-08-27 14:41 UTC
Consider the following schema:

```javascript
var user = new GraphQLObjectType({
  name: 'User',
  fields: {
    id: {
      type: GraphQLString,
    },
    config : {
      type: GraphQLString,
      resolve: function() {
        return "User123Config";
      }
    }
  }
});

var schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'RootQueryType',
    fields: {
      user: {
        type: user,
        resolve: function() {
          return { id : "123" };
        }
      }
    }
  })
});
```

And the following query:

```
{
  user {
    config
  }
}
```

In this case the resolve of the type `user` is executed when there was no need for it given that the only field in the set selection is `config` and this one has its own resolve. 
I understand that this is expected given the way selection sets are evaluated, but I am considering if this use cases were taken into consideration when designing the evaluation flow? Has a bottom-up evaluation been considered (possibly with indication of dependencies in parent fields)?

**Comment by Sandreu** [comment] 2015-09-07 01:08
Hello,

I think this really is the expected behavior... because up to bottom is the way you can handle ACL...
the config resolve's first argument will be the parent's result, in your case `{id:"123"}`

This thread #113 helps to understand GraphQL's logic, its up=>bottom... and resolve parent whatever the children's resolve can say make sense I think.

Regards.

**Comment by Sandreu** [comment] 2015-09-07 01:10
#111... :)

**Comment by leebyron** [comment] 2015-09-09 03:13
@mduarte I'm happy to entertain pull requests that investigate this. The issue I see just from reading your example case is that it would be very hard for runtime code to interpret that the "config" resolver function does not actually use the parent value, which it would need to do to decide if it can short-circuit the "user" resolver.

**Comment by leebyron** [comment] 2016-04-07 06:58
Closing this aging issue.

Note for posterity: a `resolve` function's fourth argument is a collection of interesting contextual information, including the AST that is being used for resolution. You could potentially build something today which peeks down into the AST to see if only a "cheap" field is being accessed and returns a different value which is cheaper to produce.

**Closed by leebyron** 2016-04-07 06:58 UTC
