### ISSUE TITLE
Schema documentation strings for directives

### ISSUE THREAD

**Issue by tar-aldev** [graphql/graphql-js#2461] opened 2020-02-19 16:41 UTC
I have a directive described as foolows:
```
directive @formattedDate(
    "Use moment.js formats"
    defaultFormat: String = "MMM Do YYYY"
  ) on FIELD_DEFINITION
```
As you may see I use document string for the argument.

The problem is - I don't get any documentation strings in graphql playground
https://prnt.sc/r4pnt4
Is it supported?

**Comment by IvanGoncharov** [comment] 2020-02-20 10:27
@tar-aldev Thanks for reporting 👍 
Can you please run this query against your server:
```graphql
{
  __schema {
    directives {
      name
      args {
        name
        description
      }
    }
  }
}
```
If description is present in response please report it to graphql playground repo.

**Comment by IvanGoncharov** [comment] 2020-05-06 11:33
Closing since I can't reproduce it and no additional details were provided

**Closed by IvanGoncharov** 2020-05-06 11:33 UTC
Labels: question
