### ISSUE TITLE
Query don't work [Node.js]

### ISSUE THREAD

**Issue by FlorentSebag** [graphql/graphql-js#547] opened 2016-10-28 12:47 UTC
Hi everyone,
I tried to do some requests to my database : 
![impr](https://cloud.githubusercontent.com/assets/22659490/19806725/ee647d4c-9d1c-11e6-9b31-273dcaadf8c3.png)

With the code : 
`.use('/graphql', graphqlHTTP(( req ) => {
    let sess = req.session;
    sess.ctx = {};

```
return {
    schema    : PublicSchema,
    pretty    : true,
    graphiql  : true,
    rootValue : {
      schema : 'public'
    },
    context   : sess.ctx
  };
})
```

  )

And as you can see that worked.
But when I try to do that with NodeJS, the request don't work :

```
.get('/zob', function(req, res){
    let sess = req.session;
    sess.ctx = {};
    var { graphql } = require('graphql');
    var query = 'mutation{getToken(email:"###", password:"##"){token}}';
    graphql(PublicSchema, query, sess.ctx).then((response) => {
      console.log("hey");
      console.log(response);
    });
  })
```

(I put the real email and password in my code)
And the console respond :

> { data: { getToken: { token: null } }

with error : 

> TypeError: Cannot read property 'token' of undefined

GetToken function return null...

So, i did the same thing on GraphiQL and nodeJS but with NodeJS the query don't work. Why ???

Can you help me ?
Thanks!

**Comment by stubailo** [comment] 2016-10-28 19:11
Hey, I think it's best to post this on StackOverflow on the GraphQL tag, rather than as an issue here.

**Comment by robzhu** [comment] 2016-10-28 19:53
@FlorentSebag, I just ran something similar in one of my samples and it works in both GraphiQL and calling graphql inline. I suggest looking inside your getToken resolver. Perhaps you're mishandling a promise there? 

Also, I would suggest you avoid using GraphQL for authentication operations like this. It's easy to end up with logs containing username/passwords in cleartext because you will need to add extra steps to filter GraphQL requests based on their queries.

**Comment by leebyron** [comment] 2016-11-01 02:36
It looks like you might be accessing a chain of values that ends in `token` somewhere that is undefined. @robzhu's suggestion for debugging is a good one (as is his advice on authentication).

Closing this since there is not enough information to reproduce. Feel free to reopen if you have a stack trace that blames to a bug in graphql-js

**Closed by leebyron** 2016-11-01 02:36 UTC
