### ISSUE TITLE
Permissions/Roles

### ISSUE THREAD

**Issue by raderio** [graphql/graphql-js#1001] opened 2017-08-23 11:18 UTC
Is it possible to show that some collections can be accessed only by user which has same permissions/roles?

**Comment by wincent** [comment] 2017-08-24 20:24
Sorry I didn't see this earlier, but it seems like a duplicate of #1002, which I closed in favor of discussing it on your other issue upstream (https://github.com/facebook/graphql/issues/348).

**Closed by wincent** 2017-08-24 20:24 UTC
