### ISSUE TITLE
NonNullable fields within a list cause wrong error to be reported

### ISSUE THREAD

**Issue by mikebm** [graphql/graphql-js#1680] opened 2019-01-21 19:07 UTC
When calling a resolver that returns an item that contains a list, and that list type has a NonNullable field, yet the data getting sent back is null for it, then the wrong error is reported. 

Example:
```
type Data {
   items: [LineItem]!
}

type LineItem {
    quantity: Int!
    URL: String!
}
```

If the resolver returns Data, and an item contains a URL that is null, then it reports quantity as the error.
Example response data:
```
{
   items: [
      { quantity: 1, URL: "Test1" },
      { quantity: 1, URL: "Test2" },
      { quantity: 3, URL: "Test3" },
      { quantity: 3 },
      { quantity: 1, URL: "Test5" },
   ]
}
```

Error reported in response to client:
```Cannot return null for non-nullable field LineItem.quantity.```

**Comment by IvanGoncharov** [comment] 2019-01-21 21:39
@mikebm I can reproduce this problem using following code:
```js
const {
  buildSchema,
  graphqlSync,
} = require('graphql');

const schema = buildSchema(`
  type Data {
     items: [LineItem]!
  }

  type LineItem {
      quantity: Int!
      URL: String!
  }

  schema { query: Data }
`);

const rootValue = {
   items: [
      { quantity: 1, URL: "Test1" },
      { quantity: 1, URL: "Test2" },
      { quantity: 3, URL: "Test3" },
      { quantity: 3 },
      { quantity: 1, URL: "Test5" },
   ]
};

const result = graphqlSync({
  schema,
  source: '{ items { quantity URL } }',
  rootValue,
});

console.log(JSON.stringify(result, null, 2));
```

it correctly report error as
> Cannot return null for non-nullable field LineItem.URL.

Can you please provide minimal code sample to reproduce problem that you reported?

**Comment by IvanGoncharov** [comment] 2019-01-21 23:17
> Makes me wonder if the issue is within graphql-tools then. The reason I posted here is it looked to be related to the executor when dealing with lists.

@mikebm Thanks for the code snippet. I run the debugger and it looks like graphql-tools doesn't try to correctly forward errors from merged schemas and just forward data.
BTW, the error will always mention the name of a first field from a query.
If you change it to `{ items { URL quantity } }` it will start to reporting `URL`.

**Closed by IvanGoncharov** 2019-01-21 23:17 UTC
Labels: question
