### ISSUE TITLE
Provide example through tests for mutation queries.

### ISSUE THREAD

**Issue by hekike** [graphql/graphql-js#20] opened 2015-07-04 06:02 UTC
Would be great to see some `mutation` queries.

**Comment by ilmattodel93** [comment] 2015-07-04 08:58
Possible duplicate of #14 , mutation examples are provided in the tests folder of the executor :)

https://github.com/graphql/graphql-js/blob/master/src/executor/__tests__/mutations.js

**Comment by leebyron** [comment] 2015-07-04 14:00
Yes, @dschafer wrote some pretty good tests for mutations.

**Closed by leebyron** 2015-07-04 14:00 UTC

**Comment by hekike** [comment] 2015-07-04 14:14
@leebyron ahh sry. I just missed that!

**Comment by lacker** [comment] 2016-06-14 00:09
Just mentioning, because this page keeps showing up on Google, that the above link is old, and mutation examples are in:

https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/mutations-test.js
