### ISSUE TITLE
Schema directives at field definitions are lost when a schema is parsed and printed

### ISSUE THREAD

**Issue by pmantica1** [graphql/graphql-js#2389] opened 2020-01-24 15:37 UTC
Thanks for the help on the previous issue! 

I noticed that all directives at field definitions, (excepted for the `@deprecated` directive), are lost when a schema is parsed and printed. Essentially, I noticed the following issue:
```javascript
const graphql = require("graphql");
schema = `
directive @custom_directive(a: Int) on FIELD_DEFINITION
type Object {
  a : Int @custom_directive(a: 1)
}
`
console.log(graphql.printSchema(graphql.buildASTSchema(graphql.parse(schema))));
# directive @custom_directive(a: Int) on FIELD_DEFINITION
# 
# type Object {
#   a: Int
# }
``` 
As you can see the `@custom_directive` gets lost. 

Please let me know what you think.

PS: I am using `graphql@15.0.0-alpha.2`.

**Comment by m14t** [comment] 2020-02-07 15:33
Possible related to or duplicate of #2020.

**Comment by IvanGoncharov** [comment] 2020-02-14 15:11
@pmantica1 Thanks for taking the time to report this 👍 
@m14t Is absolutely correct this is duplicate of #552 and I fully agree that this is surprising behavior and should fix it.

**Closed by IvanGoncharov** 2020-02-14 15:11 UTC
