### ISSUE TITLE
Decorated type deeper than introspection query. 4d array

### ISSUE THREAD

**Issue by TheAschr** [graphql/graphql-js#2643] opened 2020-06-10 22:08 UTC
It does not seem like this library supports 4d arrays.

I have this type defined on my server

```graphql
type MultiPolygon {
  type: GeometryType!
  coordinates: [[[[Float!]!]!]!]!
  bbox: [Float!]
}
```

When I try to load the graphql playground I get this error:

```
Uncaught Error: Decorated type deeper than introspection query.
    at m (buildClientSchema.mjs:69)
    at m (buildClientSchema.mjs:82)
    at m (buildClientSchema.mjs:72)
    at m (buildClientSchema.mjs:82)
    at m (buildClientSchema.mjs:72)
    at m (buildClientSchema.mjs:82)
    at m (buildClientSchema.mjs:72)
    at m (buildClientSchema.mjs:82)
    at w (buildClientSchema.mjs:251)
    at keyValMap.mjs:20
```

This error only occurs when I change the coordinates field from 3d to 4d.

I'm wondering if this is a bug that is fixable or is there a workaround?

**Comment by danielrearden** [comment] 2020-06-11 00:07
@TheAschr As a workaround, Playground allows you to pass in an introspection result so it won't run the initial query itself. You could modify the "official" introspection query and increase the depth of the `TypeRef` fragment

```
fragment TypeRef on __Type {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          # and so on...
```

Run this query against your schema and then pass the `data` returned to Playground as the `schema` property. If you're using Apollo, so you can pass this in as part of your configuration:

```
const server = new ApolloServer({
  schema,
  playground: {
    schema: introspectionResult
  }
});
```

Here's a [complete example](https://codesandbox.io/s/sad-bartik-l0f4i). You'll still see the error in the console if Playground attempts to fetch the introspection query again, which it does periodically by default. But at least this way, you'll have autocomplete and working schema and docs tabs.

**Comment by danielrearden** [comment] 2020-06-11 00:11
I think it might be worthwhile to add some kind of `ofTypeDepth` property to `IntrospectionOptions`, which could then also be exposed by tools like GraphiQL/GraphQL Playground.

**Comment by hally9k** [comment] 2021-05-20 01:16
Just bumped into this due to geojson multipolygons having 4d arrays for coordinates. I like the config suggestion by @danielrearden above. Also I feel like the default should be changed to support 4d arrays as geojson is becoming ubiquitous in a lot of geospatial applications so more and more people will continue to bump into this limitation.

**Comment by gf3** [comment] 2021-11-15 05:01
we also use a similar type for the same reason (MongoDB geospatial queries), i think 4d arrays are probably a saner default here

```graphql
"""
Location zone of operation.
"""
type Geometry {
  coordinates: [[[[Float!]!]!]!]!
  type: String!
}
```

**Comment by abouroubi** [comment] 2022-02-10 17:34
I'm here for the exact same reason, using GeoJSON MultiPolygon, has anything been done to solve this ?

**Comment by gf3** [comment] 2022-02-10 17:40
ping @IvanGoncharov: this issue affects anyone using GeoJSON which is built into many databases including MongoDB. seems like a relatively straightforward fix for someone familiar with the codebase

**Comment by dylandong12** [comment] 2022-02-22 22:53
we are also using GeoJSON MultiPolygon. not supporting 4d arrays blocks us from using graphql type generation tooling as well. @IvanGoncharov any idea to fix this, please?

**Comment by lars250698** [comment] 2022-04-06 07:36
I'm experiencing the same issue using [GraphQL-Kotlin](https://github.com/ExpediaGroup/graphql-kotlin), so my suspicion is that this is not a bug in the GraphQL-js library, but in [GraphQL Playground](https://github.com/graphql/graphql-playground) itself.

**Comment by drbarber** [comment] 2023-01-27 17:14
This is an error that has been plaguing me as well and I ended up resolving the issue by implementing a custom scalar as a workaround. Maybe not a perfect solution but it seems to be working well.

`export const CoordinateScalar = new GraphQLScalarType({
  name: 'coordinates',
  serialize(value) {
    return value;
  },
  parseValue(value) {
    return value;
  },
});`

**Comment by gschulze** [comment] 2023-08-02 05:30
Any update on this issue? I'm running into the same problem implementing GeoJSON input/output of MultiPolygons. Is there a timeline when this will be fixed? I'd be willing to contribute if desired.

**Closed** 2023-08-11 09:30 UTC
Labels: bug

**Comment by adriano-lupit** [comment] 2024-10-30 19:34
Use  
```
import { GraphQLJSON } from 'graphql-scalars' 
@Field(() => GraphQLJSON)
 coordinates: number[][][][];
```
