### ISSUE TITLE
NonNullable List returns null on field error

### ISSUE THREAD

**Issue by ebenoist** [graphql/graphql-js#2275] opened 2019-12-02 22:39 UTC
The return type for a non-nullable list is inconsistent with schema when a field error is present. This makes guaranteeing the type via the non-nullable contract inconsistent.

Given the following schema, it is my understanding that I should always receive an array typed object (not a null).

```gql
type Image {
  url: String!
}

type Product {
  images: [Image]!
}
```

```js
images = [] // valid
images = null // invalid
images = [null] // valid
```

However, if the resolver for images encounters an error, the returned type is `Null`.

## Recieved
```JSON
{
  "errors": [
    {
      "message": "'foozles' is not a supported image transformation.",
      "path": [
        "listing",
        "images"
      ],
      "extensions": {
        "code": "CLIENT_ERROR"
      }
    }
  ],
  "data": {
    "listing": {
      "images": null
    }
  }
}
```

This is explicitly tested for in [execution/__tests__/lists-test.js](https://github.com/graphql/graphql-js/blob/43ff3e35c699d1b6260126465b84810678d4543e/src/execution/__tests__/lists-test.js#L245-L273), but seems inconsistent with the declared type contract.

## Expected
```JSON
{
  "errors": [
    {
      "message": "'foozles' is not a supported image transformation.",
      "path": [
        "listing",
        "images"
      ],
      "extensions": {
        "code": "CLIENT_ERROR"
      }
    }
  ],
  "data": {
    "listing": {
      "images": []
    }
  }
}
```

Non-nullable types (for certain fields) allows a higher level of type safety and is especially useful while handling partial failures. 

Is this behavior intended? Is there a way to support the behavior I would have expected given the current type system and error handling behavior? There is a reference to handling this in the parent field in the [spec](https://graphql.github.io/graphql-spec/draft/#sec-Errors-and-Non-Nullability), but I'm unsure that would be consistently implemented in my resolver or parent resolver?

**Comment by yaacovCR** [comment] 2019-12-03 00:05
Try:

```
type Product {
  images: [Image!]!
}
```

Note the inner exclamation point

:)

**Comment by ebenoist** [comment] 2019-12-03 15:19
@yaacovCR That's not issue I am running into. Changing this to `[Image!]!` makes the following invalid `[null]`, but doesn't fix the issue of allowing `null` to be returned when images returns an error.

**Comment by yaacovCR** [comment] 2019-12-03 15:35
Sorry, read too fast!

**Comment by danielrearden** [comment] 2020-06-06 11:38
If `images` has a non-null type and an error is thrown inside its resolver, then its *parent* field will instead return null because `images` can never be null. If the parent also has a non-null type, then *its* parent will be null, and so on until we hit either a nullable field or `data` (which is always nullable).

In other words, assuming `listing` is nullable, if an error is thrown inside `images`, the expected response would be `{ data: { listing: null } }`. If `listing` is also non-null, the expected response would be `{ data: null }`.

`images` returning null when it's a non-null field would be a spec-breaking behavior and a bug. However, I cannot reproduce this behavior on my end.

If you want `images` to return an empty array when an error is encountered during the execution of its resolver, you'd need to wrap the resolver logic in a try/catch and return the empty array inside the catch block.

@ebenoist I'm closing this issue since I can't seem to reproduce it. If you are still seeing this behavior, it would be great if you could provide a code snippet or code sandbox to reproduce it. If you have additional questions about GraphQL, please post them on SO since we use issues only for tracking bugs and feature requests.

**Closed by danielrearden** 2020-06-06 11:38 UTC
Labels: question
