### ISSUE TITLE
"one instance of graphql" error when using esm package.

### ISSUE THREAD

**Issue by Pokute** [graphql/graphql-js#1479] opened 2018-08-24 10:45 UTC
When using `esm` package (https://github.com/standard-things/esm) even most simple package.json configurations (only dependancies are `esm` and `graphql-yoga`) results in the `Error: Cannot use GraphQLSchema "[object Object]" from another module or realm.` error when using imports.

`node -r esm testWithImport.js` will fail while `node testWithRequire.js` and `node -r esm testWithRequire.js` will work.

**Comment by IvanGoncharov** [comment] 2018-08-24 12:40
@Pokute Can you please setup sample repo to reproduce this issue?

**Comment by IvanGoncharov** [comment] 2018-08-24 12:42
@Pokute Can you also run `npm ls graphql` and post the output here?

**Comment by Pokute** [comment] 2018-08-28 07:28
Repo for reproducing: https://github.com/Pokute/graphql-esm-bug

**Comment by jdalton** [comment] 2018-08-28 19:53
This happens if you were to add a new npm script called
```
"mjsImport": "node --experimental-modules serverWithImport.mjs"
```
and a test file `serverWithImport.mjs`:
```js
import graphglYoga from 'graphql-yoga';
import { GraphQLObjectType, GraphQLSchema, GraphQLString } from "graphql";

const { GraphQLServer } = graphglYoga

var Something = new GraphQLObjectType({
    fields: {
        else: { type: GraphQLString },
    },
    name: 'Something',
})

var schema = new GraphQLSchema({
    query: new GraphQLObjectType({
        fields: {
            something: {
                type: Something,
            },
        },
        name: 'Query',
    }),
});

var server = new GraphQLServer({ schema });
const instance = server.start(); // defaults to port 4000
```
too.

The issue is that `graphql-yoga` is CJS _(and loads the CJS entry of `graphql`)_ but you're loading the ESM version of `graphql`. 

Because `graphgl` is running two entry points they create 2 separate instances (a limitation of their current dual approach). The way around it is for `graphql` to instantiate their instances in CJS and export them for the ESM entry to consume.

**Comment by IvanGoncharov** [comment] 2018-08-28 20:56
@jdalton Thanks for detail response. I have a few questions about the proposed solution:
> The way around it is for graphql to instantiate their instances in CJS and export them for the ESM entry to consume.

Is it something like this?
`index.mjs`
```js
const {
  GraphQLObjectType,
  // ....
} = require('./graphql');

export GraphQLObjectType;
// ...
```

If so, it makes tree shaking impossible, right?
This library is pretty big and it's released as a single package so tree shaking is the only option to make it usable on the frontend.
So we can't make any changes that will break tree shaking support in Webpack or any other bundler.

**Comment by jdalton** [comment] 2018-08-28 21:15
@IvanGoncharov 
> Is it something like this?

No. That wouldn't work in `.mjs` anyways since `require` doesn't exist. The idea is that the `GraphQLObjectType` is defined in CJS and then used by the ESM build as well.
```js
import GraphQLObjectType from "./types/object.js"
```
The other option is to drop `instanceof` checks and move to a check for the existence of say a non-enumerable symbol property.

**Comment by jdalton** [comment] 2018-08-28 22:48
> AFAIK, IE doesn't support Symbol so we can't use it.

core-js has a [shim for it](https://github.com/zloirock/core-js#ecmascript-symbol). You could also use any-other property to detect the instance `object.__COULD_BE_THIS_KIND_OF_PROPERTY__`.

> So if ESM declares it supports MJS format it should ensure that only one instance of the library is created.

This is not an `esm` issue as mentioned this presents itself with `--experimental-modules` too. The issue is that `graphql` has 2 entry points for the package.

> For now, I think the most practical solution would be to open a feature request against `graphql-yoga` to also ship mjs files.

FWIW I'm a Node core member and a member of the Node Module Working Group. Our recommendation is to not adopt `--experimental-modules` for production use.

**Comment by arackaf** [comment] 2018-09-11 22:50
Just removing the .mjs entry point might be a good interim solution. Is anyone even using .mjs in production? Plenty of people are using esm, and this is causing hard-to-track bugs.

**Comment by rosendi** [comment] 2018-09-23 07:30
@jdalton thank you for v3.0.83!

**Comment by IvanGoncharov** [comment] 2018-09-23 11:28
@jdalton Thanks for fixing it in ESM.

**Closed by IvanGoncharov** 2018-09-23 11:28 UTC
Labels: needs exploration

**Comment by jdalton** [comment] 2018-09-23 16:14
Just a heads up this doesn't fix `graphql` with Node's native `--experimental-modules`. Your problem still exists. Other projects like Create React App 2.0 are removing `.mjs` until issues, like these, can be worked out.

**Comment by jdalton** [comment] 2018-09-28 19:57
Related https://github.com/graphql/graphql-js/issues/1536.

**Comment by jdalton** [comment] 2018-09-29 03:59
@jaydenseric 

> That's bad news, people rely on the proper Node.js resolution order.

It's not so bad when the alternative is non-working code. For `esm` the resolution order is configurable via `options.cjs.paths` _(defaults to `true`)_.

> This issue is being over complicated. `graphql-yoga` should provide a `.mjs` build then the issue will go away. As a bonus native ESM in Node.js would be supported without having to use the `esm` package.

👋 Node core and Node Module WG member here. There is no set date for when `--experimental-modules` will be unflagged. There's also no guarantee that what has shipped now is what will be in the future. For example, there are several discussions in the Node Module WG on how to approach implementation. One such discussion is to ship a maximally minimal implementation that would require package-maps for resolving bare specifiers _(no longer using the Node module resolution algorithm)_. 

Adopting `.mjs` with the idea that its current support is solid _(for production use)_ at this stage is bit premature and may cause headaches for users. I've already seen `.mjs` cause issues for real projects like create-react-app, pm2, react-apollo, and webpack due to complications with transpilers/bundlers, testing/mocks, or dual packages. Also, if/when changes do happen to Node's `--experimental-modules` your ESM story may be various shades of broken.

The `--experimental-modules` flag really does mean experimental. It's something you should pause and consider at least before going all in on it as the route for your ESM support strategy today.

**Comment by hsanoyan** [comment] 2019-07-31 13:59
My solution was to replace
```js
import graphql from 'graphql'
```
with
```js
import graphql from 'graphql/index.js'
```
I was using flags `--experimental-modules --es-module-specifier-resolution=node` to omit extensions.
